// Generated by js_of_ocaml
//# buildInfo:effects=false, kind=cmo, use-js-string=true, version=5.8.2

//# unitInfo: Provides: Dune__exe__SpletniVmesnik
//# unitInfo: Requires: Definicije__Avtomat, Dune__exe__Model, Dune__exe__View, Js_browser, Stdlib__Array, Vdom, Vdom_blit
(function
  (globalThis){
   "use strict";
   var runtime = globalThis.jsoo_runtime;
   function caml_call1(f, a0){
    return (f.l >= 0 ? f.l : f.l = f.length) == 1
            ? f(a0)
            : runtime.caml_call_gen(f, [a0]);
   }
   function caml_call2(f, a0, a1){
    return (f.l >= 0 ? f.l : f.l = f.length) == 2
            ? f(a0, a1)
            : runtime.caml_call_gen(f, [a0, a1]);
   }
   function caml_call3(f, a0, a1, a2){
    return (f.l >= 0 ? f.l : f.l = f.length) == 3
            ? f(a0, a1, a2)
            : runtime.caml_call_gen(f, [a0, a1, a2]);
   }
   function caml_call4(f, a0, a1, a2, a3){
    return (f.l >= 0 ? f.l : f.l = f.length) == 4
            ? f(a0, a1, a2, a3)
            : runtime.caml_call_gen(f, [a0, a1, a2, a3]);
   }
   var
    global_data = runtime.caml_get_global_data(),
    Vdom_blit = global_data.Vdom_blit,
    Js_browser = global_data.Js_browser,
    Stdlib_Array = global_data.Stdlib__Array,
    Dune_exe_View = global_data.Dune__exe__View,
    Dune_exe_Model = global_data.Dune__exe__Model,
    Definicije_Avtomat = global_data.Definicije__Avtomat,
    Vdom = global_data.Vdom,
    _a_ = Dune_exe_View[13],
    _b_ = Dune_exe_Model[3],
    _c_ = caml_call3(Dune_exe_Model[1], 500., 500., Definicije_Avtomat[10]),
    app = caml_call4(Vdom[64], _c_, _b_, _a_, 0),
    cst_container = "container";
   function run(param){
    var
     _d_ = caml_call3(Vdom_blit[11], 0, 0, app),
     _e_ = caml_call1(Vdom_blit[13], _d_),
     _f_ = caml_call2(Js_browser[16][8], Js_browser[26], cst_container),
     match = caml_call1(Stdlib_Array[10], _f_);
    if(match)
     var element = match[1], element$0 = element;
    else
     var element$0 = caml_call1(Js_browser[16][10], Js_browser[26]);
    return caml_call1(caml_call1(Js_browser[15][9], element$0), _e_);
   }
   caml_call2(Js_browser[19][6], Js_browser[25], run);
   var Dune_exe_SpletniVmesnik = [0];
   runtime.caml_register_global
    (10, Dune_exe_SpletniVmesnik, "Dune__exe__SpletniVmesnik");
   return;
  }
  (globalThis));

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLjAsImZpbGUiOiIuc3BsZXRuaVZtZXNuaWsuZW9ianMvanNvby9kdW5lX19leGVfX1NwbGV0bmlWbWVzbmlrLmNtby5qcyIsInNvdXJjZVJvb3QiOiIiLCJuYW1lcyI6WyJhcHAiLCJydW4iLCJlbGVtZW50IiwiZWxlbWVudCQwIl0sInNvdXJjZXMiOlsiL3dvcmtzcGFjZV9yb290L3NyYy9zcGxldG5pVm1lc25pay9zcGxldG5pVm1lc25pay5tbCJdLCJtYXBwaW5ncyI6Ijs7Ozs7Ozs7O0c7Ozs7O0c7Ozs7O0c7Ozs7O0c7Ozs7O0dBRVU7Ozs7Ozs7Ozs7O0lBQUEsTUFBQTtJQUZOQSxNQUNGOztZQU1JQztJQUNGO0tBQUEsTUFBQSxnQ0FSQUQ7S0FRQSxNQUFBO0tBR1EsTUFBQTtLQUFBLFFBQUE7O1NBSURFLG9CQUFBQyxZQUFBRDs7U0FBQUMsWUFDTTtJQVJiLE9BQUEsV0FDRyw4QkFNSUE7R0FDK0Q7R0FFeEUsOENBWElGOzs7OztFIiwic291cmNlc0NvbnRlbnQiOlsibGV0IGFwcCA9XG4gIFZkb20uc2ltcGxlX2FwcFxuICAgIH5pbml0OihNb2RlbC5pbml0IDUwMC4gNTAwLiBEZWZpbmljaWplLkF2dG9tYXQuZW5rZV8xbW9kMylcbiAgICB+dmlldzpWaWV3LnZpZXcgfnVwZGF0ZTpNb2RlbC51cGRhdGUgKClcblxubGV0ICgpID1cbiAgbGV0IG9wZW4gSnNfYnJvd3NlciBpblxuICBsZXQgcnVuICgpID1cbiAgICBWZG9tX2JsaXQucnVuIGFwcCB8PiBWZG9tX2JsaXQuZG9tXG4gICAgfD4gSnNfYnJvd3Nlci5FbGVtZW50LmFwcGVuZF9jaGlsZFxuICAgICAgICAgKG1hdGNoXG4gICAgICAgICAgICBKc19icm93c2VyLkRvY3VtZW50LmdldF9lbGVtZW50c19ieV9jbGFzc19uYW1lIEpzX2Jyb3dzZXIuZG9jdW1lbnRcbiAgICAgICAgICAgICAgXCJjb250YWluZXJcIlxuICAgICAgICAgICAgfD4gQXJyYXkudG9fbGlzdFxuICAgICAgICAgIHdpdGhcbiAgICAgICAgIHwgZWxlbWVudCA6OiBfIC0+IGVsZW1lbnRcbiAgICAgICAgIHwgW10gLT4gSnNfYnJvd3Nlci5Eb2N1bWVudC5kb2N1bWVudF9lbGVtZW50IEpzX2Jyb3dzZXIuZG9jdW1lbnQpXG4gIGluXG4gIFdpbmRvdy5zZXRfb25sb2FkIHdpbmRvdyBydW5cbiJdfQ==
